SELECT NATIONALIDNUMBER,HIREDATE,VACATIONHOURS,
CASE 
-- Print  when vacution hour is > 70 in VACMSG column
WHEN VACATIONHOURS > 70 THEN 'EXCEDED LIMIT'
-- Print  when vacution hour in between 40 and  70 in VACMSG column
WHEN VACATIONHOURS BETWEEN 40 AND 70 THEN 'AVERAGE LIMIT'
-- else print in VACMSG Column
ELSE 'WITHIN LIMIT'
END AS 'VACMSG'
FROM HUMANRESOURCES.EMPLOYEE