SELECT TITLE,FIRSTNAME,MIDDLENAME,LASTNAME,TITLE+FIRSTNAME+MIDDLENAME+LASTNAME AS FULLNAME
FROM PERSON.PERSON

SELECT TITLE,FIRSTNAME,MIDDLENAME,LASTNAME,
CONCAT( TITLE,FIRSTNAME,MIDDLENAME,LASTNAME) AS FULLNAME
FROM PERSON.PERSON

SELECT TITLE,FIRSTNAME,MIDDLENAME,LASTNAME,
CONCAT( TITLE,FIRSTNAME,MIDDLENAME,LASTNAME,'@',CONCAT_WS('.','TESTDOMAIN','COM')) AS FULLNAME
FROM PERSON.PERSON

