SELECT NATIONALIDNUMBER,JOBTITLE,BIRTHDATE,MARITALSTATUS 
FROM HUMANRESOURCES.EMPLOYEE
--<> means not equal
WHERE MARITALSTATUS <> 'M' 
--year is a function to get year ffrom date
AND YEAR(BIRTHDATE)>='1986'


----------------------Using Arthamatic operation-------
SELECT NAME,PRODUCTNUMBER
FROM PRODUCTION.PRODUCT
WHERE STANDARDCOST+LISTPRICE>0